services:
  sadrafars:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - external-net
    dns:
      - 217.218.127.127
      - 1.1.1.1

networks:
  external-net:
    external: true
