name: Deploy sadrafars (Direct Clone)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: sadrafars
    steps:
      - name: Checkout repository
        shell: bash
        run: |
          set -e

          REPO_URL="ssh://git@87.248.139.251:2222/ARACOM/sadrafars.ir.git"
          BRANCH="${{ gitea.ref_name }}"

          rm -rf repo
          git clone --depth 1 --branch "$BRANCH" "$REPO_URL" repo

      - name: Deploy
        shell: bash
        run: |
          set -e
          cd repo
          
          echo "Deploying..."
          docker compose down -v || true
          docker compose up -d --build

          git clean -fdx || true
