name: Deploy sadrafars (Direct Clone)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: changed

    steps:
      - name: Checkout repository
        shell: bash
        run: |
          set -e

          REPO_URL="ssh://git@87.248.139.251:2222/ARACOM/sadrafars.ir.git"

          rm -rf repo
          git clone --depth 1 --branch main "$REPO_URL" repo

      - name: Deploy
        shell: bash
        run: |
          set -e

          cd repo

          echo "Deploying production..."
          export IMAGE_TAG="latest"

          docker compose up -d --build sadrafars

          git clean -fdx || true